use crate::manifest::Manifest;
use anyhow::Result;
use chrono::Utc;
use std::path::Path;

use crate::ContextCmd;

pub fn run(store_root: &Path, cmd: ContextCmd) -> Result<()> {
    match cmd {
        ContextCmd::Show => {
            let context_file = store_root.join("context.md");
            if !context_file.exists() {
                println!("No context.md found. Run `docmgr context refresh` to generate.");
                return Ok(());
            }
            let content = std::fs::read_to_string(&context_file)?;
            print!("{}", content);
        }
        ContextCmd::Update { statement } => {
            let updates_file = store_root.join(".docmgr").join("context_updates.jsonl");
            let entry = serde_json::json!({
                "timestamp": Utc::now().to_rfc3339(),
                "update": statement,
                "incorporated": false,
            });
            let mut content = if updates_file.exists() {
                std::fs::read_to_string(&updates_file)?
            } else {
                String::new()
            };
            content.push_str(&entry.to_string());
            content.push('\n');
            std::fs::write(&updates_file, content)?;
            println!("Context update queued: {}", statement);
        }
        ContextCmd::Updates => {
            let updates_file = store_root.join(".docmgr").join("context_updates.jsonl");
            if !updates_file.exists() {
                println!("No pending context updates.");
                return Ok(());
            }
            let content = std::fs::read_to_string(&updates_file)?;
            let pending: Vec<_> = content
                .lines()
                .filter(|l| !l.trim().is_empty())
                .filter_map(|l| serde_json::from_str::<serde_json::Value>(l).ok())
                .filter(|v| !v["incorporated"].as_bool().unwrap_or(false))
                .collect();

            if pending.is_empty() {
                println!("No pending context updates.");
            } else {
                println!("{} pending update(s):", pending.len());
                for u in &pending {
                    println!(
                        "  [{}] {}",
                        u["timestamp"].as_str().unwrap_or(""),
                        u["update"].as_str().unwrap_or("")
                    );
                }
            }
        }
        ContextCmd::Refresh => {
            let manifest = Manifest::load(store_root)?;
            let plans = manifest.list(Some(&crate::types::DocType::Plan));
            let refs = manifest.list(Some(&crate::types::DocType::Reference));

            // Without LLM: generate a structured template.
            let mut out = String::from("# Project Context\n\n");
            out.push_str("*Auto-generated by docmgr. Use `docmgr context refresh` to update.*\n\n");

            out.push_str("## Plans\n\n");
            for p in &plans {
                out.push_str(&format!("- {} — {}\n", p.path.display(), p.description));
            }
            out.push('\n');

            out.push_str("## Reference\n\n");
            for r in &refs {
                out.push_str(&format!("- {} — {}\n", r.path.display(), r.description));
            }

            std::fs::write(store_root.join("context.md"), &out)?;
            println!("context.md refreshed ({} plans, {} reference docs).", plans.len(), refs.len());
        }
    }
    Ok(())
}
